"use client"

//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Navigation";
import FinanceContextProvider from "@/lib/store/finance-context"
import AuthContextProvider from "@/lib/store/auth-context"

//const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      
      <body>
        <AuthContextProvider>
        <FinanceContextProvider>
    <Nav/>
        {children}
    </FinanceContextProvider>
        </AuthContextProvider>

    {/* <FinanceContextProvider>
    <Nav/>
        {children}
    </FinanceContextProvider> */}
       
    
      
        </body>
    </html>
  );
}
